const getWeapons = () => {

    const weapons = {
        "Assault Rifles": [
            {
                "name": "Kilo 141",
                "description": "Fully automatic assault rifle with an ergonomic design that improves handling, and a steady fire rate helps stay on target.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/kilo-141.jpg",
                "class": "Assault Rifles",
                "accuracy": 70,
                "damage": 73,
                "range": 64,
                "fire_rate": 73,
                "mobility": 61,
                "control": 72,
                "overall": 68.83,
                "price": 8900
            },
            {
                "name": "FAL",
                "description": "Semi-automatic battle rifle with a high rate of fire for faster follow up shots.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/fal.jpg",
                "class": "Assault Rifles",
                "accuracy": 74,
                "damage": 79,
                "range": 70,
                "fire_rate": 59,
                "mobility": 60,
                "control": 68,
                "overall": 68.33,
                "price": 6700
            },
            {
                "name": "M4A1",
                "description": "Fully automatic, all-purpose battle rifle. Control your shots, and this weapon can be very effective at range.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/m4a1.jpg",
                "class": "Assault Rifles",
                "accuracy": 71,
                "damage": 72,
                "range": 63,
                "fire_rate": 75,
                "mobility": 63,
                "control": 71,
                "overall": 69.17,
                "price": 8000
            },
            {
                "name": "FR 5.56",
                "description": "3 round burst bullpup battle rifle. A well placed burst can be extremely deadly at intermittent range.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/fr-556.jpg",
                "class": "Assault Rifles",
                "accuracy": 73,
                "damage": 75,
                "range": 62,
                "fire_rate": 72,
                "mobility": 58,
                "control": 72,
                "overall": 68.67,
                "price": 6500
            },
            {
                "name": "Oden",
                "description": "Fully automatic bullpup battle rifle maintains a slow cycle rate to help control hard hitting 12.7x55mm ammunition.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/oden.jpg",
                "class": "Assault Rifles",
                "accuracy": 65,
                "damage": 79,
                "range": 68,
                "fire_rate": 58,
                "mobility": 56,
                "control": 60,
                "overall": 64.33,
                "price": 8000
            },
            {
                "name": "M13",
                "description": "Automatic assault rifle featuring a short-stroke piston system that keeps the fire rate high and the recoil low.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/m13.jpg",
                "class": "Assault Rifles",
                "accuracy": 72,
                "damage": 71,
                "range": 64,
                "fire_rate": 77,
                "mobility": 62,
                "control": 74,
                "overall": 70.0,
                "price": 8000
            },
            {
                "name": "FN Scar 17",
                "description": "Large caliber, fully automatic assault rifle that provides high damage over long ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/fn-scar-17.jpg",
                "class": "Assault Rifles",
                "accuracy": 69,
                "damage": 76,
                "range": 68,
                "fire_rate": 63,
                "mobility": 57,
                "control": 65,
                "overall": 66.33,
                "price": 8000
            },
            {
                "name": "AK-47",
                "description": "Very reliable automatic assault rifle chambered in 7.62mm Soviet. Large caliber ammunition requires skill to control recoil.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/ak-47.jpg",
                "class": "Assault Rifles",
                "accuracy": 68,
                "damage": 76,
                "range": 67,
                "fire_rate": 61,
                "mobility": 59,
                "control": 68,
                "overall": 66.5,
                "price": 8000
            },
            {
                "name": "RAM-7",
                "description": "Fully automatic bullpup assault rifle with a compact design that lends itself to close quarters engagements.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/ram-7.jpg",
                "class": "Assault Rifles",
                "accuracy": 70,
                "damage": 73,
                "range": 60,
                "fire_rate": 76,
                "mobility": 66,
                "control": 73,
                "overall": 69.67,
                "price": 8000
            },
            {
                "name": "Grau 5.56",
                "description": "This modular 5.56 weapon platform is lightweight and maneuverable, with exceptional range.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/grau-556.jpg",
                "class": "Assault Rifles",
                "accuracy": 70,
                "damage": 72,
                "range": 66,
                "fire_rate": 72,
                "mobility": 65,
                "control": 70,
                "overall": 69.17,
                "price": 8000
            },
            {
                "name": "CR-56 AMAX",
                "description": "This lightweight 7,62 x 39mm full-auto assault rifle is compact and powerful. Built exclusively for military use, the standard issue rifle is deadly at mid-range combat and easily configured for a variety of assault rifles.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/cr-56-amax.jpg",
                "class": "Assault Rifles",
                "accuracy": 69,
                "damage": 76,
                "range": 65,
                "fire_rate": 66,
                "mobility": 62,
                "control": 69,
                "overall": 67.83,
                "price": 8000
            },
            {
                "name": "AN-94",
                "description": "Cutting edge 5.45x39mm Russian rifle with a unique hyperburst feature. The initial shot from each trigger pull fires a rapid 2-round burst before perceived recoil is felt, creating a tightly grouped cluster with increased damage potential. This mechanism is fed by a canted magazine, and a reciprocating receiver helps keep control of the recoil.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/an-94.jpg",
                "class": "Assault Rifles",
                "accuracy": 74,
                "damage": 73,
                "range": 62,
                "fire_rate": 68,
                "mobility": 62,
                "control": 71,
                "overall": 68.33,
                "price": 8000
            },
            {
                "name": "AS VAL",
                "description": "This assault rifle, the 13th member of this weapon category, is a rare Soviet powerhouse chambered in subsonic 9x39mm ammunition and is pre-equipped with an integral suppressor. Combined with the weapon\u2019s high rate of fire, the AS-VAL is built for stealth, accuracy, and high penetration, all on a highly configurable platform.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/as-val.jpg",
                "class": "Assault Rifles",
                "accuracy": 69,
                "damage": 76,
                "range": 59,
                "fire_rate": 77,
                "mobility": 64,
                "control": 69,
                "overall": 69.0,
                "price": 8000
            }
        ],
        "SMGs": [
            {
                "name": "AUG",
                "description": "A modular fully automatic weapon configured for mobility and close range combat.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/aug.jpg",
                "class": "SMGs",
                "accuracy": 67,
                "damage": 70,
                "range": 58,
                "fire_rate": 72,
                "mobility": 65,
                "control": 72,
                "overall": 67.33,
                "price": 3600
            },
            {
                "name": "P90",
                "description": "Automatic bullpup submachine gun. A Unique top mounted magazine hold carries ample high velocity 5.7x28mm ammunition.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/p90.jpg",
                "class": "SMGs",
                "accuracy": 69,
                "damage": 65,
                "range": 52,
                "fire_rate": 78,
                "mobility": 70,
                "control": 74,
                "overall": 68.0,
                "price": 4350
            },
            {
                "name": "MP5",
                "description": "Fully automatic 9mm submachine gun. A perfect balance of stability, mobility, and lethality.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/mp5.jpg",
                "class": "SMGs",
                "accuracy": 66,
                "damage": 69,
                "range": 55,
                "fire_rate": 75,
                "mobility": 73,
                "control": 77,
                "overall": 69.17,
                "price": 4550
            },
            {
                "name": "Uzi",
                "description": "Fully automatic open bolt submachine gun. Simple, steady, and effective.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/uzi.jpg",
                "class": "SMGs",
                "accuracy": 61,
                "damage": 70,
                "range": 49,
                "fire_rate": 64,
                "mobility": 78,
                "control": 78,
                "overall": 66.67,
                "price": 4100
            },
            {
                "name": "PP19 Bizon",
                "description": "Well balanced automatic submachine gun with a high capacity helical magazine.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/pp19-bizon.jpg",
                "class": "SMGs",
                "accuracy": 64,
                "damage": 72,
                "range": 53,
                "fire_rate": 67,
                "mobility": 68,
                "control": 75,
                "overall": 66.5,
                "price": 4200
            },
            {
                "name": "MP7",
                "description": "Compact by deisgn, this fully automatic weapon has a high rate of fire and low recoil.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/mp7.jpg",
                "class": "SMGs",
                "accuracy": 63,
                "damage": 64,
                "range": 47,
                "fire_rate": 79,
                "mobility": 75,
                "control": 76,
                "overall": 67.33,
                "price": 4600
            },
            {
                "name": "Striker 45",
                "description": "A hard hitting submachine gun chambered in .45 Auto that will shred at longer distances than other weapons in its class.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/striker-45.jpg",
                "class": "SMGs",
                "accuracy": 68,
                "damage": 75,
                "range": 61,
                "fire_rate": 64,
                "mobility": 72,
                "control": 72,
                "overall": 68.67,
                "price": 3000
            },
            {
                "name": "Fennec",
                "description": "An aggressive full auto sub machine gun with buttery smooth recoil and a blazing fast rate of fire that is exceptional for strategic room cleaning and holding down the front line.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/fennec.jpg",
                "class": "SMGs",
                "accuracy": 71,
                "damage": 65,
                "range": 50,
                "fire_rate": 82,
                "mobility": 70,
                "control": 73,
                "overall": 68.5,
                "price": 3800
            },
            {
                "name": "ISO",
                "description": "Precision crafted 9mm submachine gun with a fast rate of fire. This lightweight and reliable firearm is designed to control the close-range battlefield.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/iso.jpg",
                "class": "SMGs",
                "accuracy": 65,
                "damage": 68,
                "range": 51,
                "fire_rate": 77,
                "mobility": 74,
                "control": 77,
                "overall": 68.67,
                "price": 3200
            },
            {
                "name": "CX-9",
                "description": "Excellent maneuverability and a fast fire rate make this blowback-operated SMG a formidable weapon in close-quarters engagements.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/cx-9.jpg",
                "class": "SMGs",
                "accuracy": 65,
                "damage": 66,
                "range": 52,
                "fire_rate": 81,
                "mobility": 79,
                "control": 74,
                "overall": 69.5,
                "price": 3400
            }
        ],
        "Shotguns": [
            {
                "name": "Model 680",
                "description": "Reliable, well rounded 12 gauge pump-action shotgun.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/model-680.jpg",
                "class": "Shotguns",
                "accuracy": 60,
                "damage": 82,
                "range": 45,
                "fire_rate": 45,
                "mobility": 69,
                "control": 65,
                "overall": 61.0,
                "price": 2500
            },
            {
                "name": "R9-0 Shotgun",
                "description": "Double barrels provide two rapid shots before each re-chamber.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/r9-0-shotgun.jpg",
                "class": "Shotguns",
                "accuracy": 55,
                "damage": 79,
                "range": 42,
                "fire_rate": 51,
                "mobility": 71,
                "control": 75,
                "overall": 62.17,
                "price": 2500
            },
            {
                "name": "725",
                "description": "Break action shotgun with 2 round capacity. A long back-bored barrel and cylindrical choke keeps spread tight and lethal over extended ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/725.jpg",
                "class": "Shotguns",
                "accuracy": 70,
                "damage": 85,
                "range": 56,
                "fire_rate": 50,
                "mobility": 62,
                "control": 60,
                "overall": 63.83,
                "price": 2700
            },
            {
                "name": "Origin 12",
                "description": "Semi-automatic shotgun with large ammo capacity allows for continuous firing. Effective at close range.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/origin-12-shotgun.jpg",
                "class": "Shotguns",
                "accuracy": 50,
                "damage": 76,
                "range": 38,
                "fire_rate": 49,
                "mobility": 76,
                "control": 70,
                "overall": 59.83,
                "price": 3300
            },
            {
                "name": "VLK Rogue",
                "description": "An agile 12-gauge mag fed shotgun from VLK with extensive option to modify range, stability, and maneuverability.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/vlk-rogue.jpg",
                "class": "Shotguns",
                "accuracy": 57,
                "damage": 78,
                "range": 42,
                "fire_rate": 51,
                "mobility": 78,
                "control": 68,
                "overall": 62.33,
                "price": 3200
            },
            {
                "name": "JAK-12",
                "description": "Fully automatic open bolt shotgun with a recoil-reducing gas blowback system. This combat shotgun unloads high volumes of lead down range at a steady rate.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/jak-12.jpg",
                "class": "Shotguns",
                "accuracy": 56,
                "damage": 75,
                "range": 40,
                "fire_rate": 53,
                "mobility": 70,
                "control": 73,
                "overall": 61.17,
                "price": 5600
            }
        ],
        "LMGs": [
            {
                "name": "PKM",
                "description": "Fully automatic light machine gun firing 7.62mm ammunition for high damage at a moderate fire rate.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/pkm.jpg",
                "class": "LMGs",
                "accuracy": 75,
                "damage": 77,
                "range": 76,
                "fire_rate": 68,
                "mobility": 50,
                "control": 65,
                "overall": 68.5,
                "price": 9000
            },
            {
                "name": "SA87",
                "description": "Fully automatic bullpup light machine gun. Lower rate of fire and 5.56mm ammunition keeps this rifle stable and effective at long ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/sa87.jpg",
                "class": "LMGs",
                "accuracy": 73,
                "damage": 74,
                "range": 77,
                "fire_rate": 64,
                "mobility": 53,
                "control": 70,
                "overall": 68.5,
                "price": 8400
            },
            {
                "name": "M91",
                "description": "Robust light machine gun sacrifices mobility for stability. High caliber sustained fire will neutralize targets at long ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/m91.jpg",
                "class": "LMGs",
                "accuracy": 74,
                "damage": 76,
                "range": 77,
                "fire_rate": 66,
                "mobility": 51,
                "control": 65,
                "overall": 68.17,
                "price": 9300
            },
            {
                "name": "MG34",
                "description": "Fully automatic weapon with a high rate of fire and punishing 7.92 Mauser ammunition. Salvaged WW2 machine guns are still reliable and deadly on the battlefield.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/mg34.jpg",
                "class": "LMGs",
                "accuracy": 72,
                "damage": 77,
                "range": 78,
                "fire_rate": 70,
                "mobility": 48,
                "control": 72,
                "overall": 69.5,
                "price": 4300
            },
            {
                "name": "Holger-26",
                "description": "Versatile fully automatic 5.56mm light machine gun. Modular design can be configured for a broad range of engagements.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/holger-26.jpg",
                "class": "LMGs",
                "accuracy": 73,
                "damage": 73,
                "range": 76,
                "fire_rate": 70,
                "mobility": 52,
                "control": 72,
                "overall": 69.33,
                "price": 10200
            },
            {
                "name": "Bruen MK9",
                "description": "Add some more firepower to your arsenal with the MK9 Bruen LMG. This high accuracy and reliable damage weapon can be acquired via the \u2018Encryption\u2019 bundle or by completing a challenge found in the Weapons menu. Head to the LMG tab to find LMG Foxtrot and complete the associated challenge to earn the weapon or get the Legendary \u2018The Glitch\u2019 blueprint in the \u2018Encryption\u2019 bundle in the Store.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/MK9-Bruen.jpg",
                "class": "LMGs",
                "accuracy": 78,
                "damage": 73,
                "range": 74,
                "fire_rate": 73,
                "mobility": 52,
                "control": 69,
                "overall": 69.83,
                "price": 7800
            },
            {
                "name": "FiNN LMG",
                "description": "An ultra-light open bolt 5.56 machine gun with a low cyclic rate and advanced recoil controls, giving the FiNN exceptional full-auto accuracy.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/finn-lmg.jpg",
                "class": "LMGs",
                "accuracy": 79,
                "damage": 74,
                "range": 72,
                "fire_rate": 66,
                "mobility": 54,
                "control": 73,
                "overall": 69.67,
                "price": 6500
            },
            {
                "name": "RAAL MG",
                "description": "The Reconnaissance Auxiliary Assault Lightweight Machine Gun uses a low fire rate and a reciprocating barrel to mitigate the powerful .338 Normal Mag recoil. Advanced titanium construction keeps the weight manageable.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/raal-mg.jpg",
                "class": "LMGs",
                "accuracy": 71,
                "damage": 81,
                "range": 82,
                "fire_rate": 63,
                "mobility": 47,
                "control": 64,
                "overall": 68.0,
                "price": 13400
            }
        ],
        "Marksman Rifles": [
            {
                "name": "EBR-14",
                "description": "Semi-automatic long range battle rifle balances rate of fire with lethality.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/ebr-14.jpg",
                "class": "Marksman Rifles",
                "accuracy": 77,
                "damage": 76,
                "range": 73,
                "fire_rate": 57,
                "mobility": 58,
                "control": 72,
                "overall": 68.83,
                "price": 4800
            },
            {
                "name": "MK2 Carbine",
                "description": "Highly accurate lever action rifle. Will neutralize an enemy with one well placed round to the head or chest.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/mk2-carbine.jpg",
                "class": "Marksman Rifles",
                "accuracy": 78,
                "damage": 80,
                "range": 68,
                "fire_rate": 45,
                "mobility": 66,
                "control": 60,
                "overall": 66.17,
                "price": 5400
            },
            {
                "name": "Kar98k",
                "description": "Bolt action rifle chambered in 7.62 Mauser. A WW2 relic that is still extremely lethal in the hands of a rebel marksman.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/kar98k.jpg",
                "class": "Marksman Rifles",
                "accuracy": 76,
                "damage": 82,
                "range": 75,
                "fire_rate": 41,
                "mobility": 53,
                "control": 68,
                "overall": 65.83,
                "price": 6000
            },
            {
                "name": "Crossbow",
                "description": "Silent and agile, this high-performance crossbow fires 20.0\" bolts with exceptional lethality.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/crossbow.jpg",
                "class": "Marksman Rifles",
                "accuracy": 70,
                "damage": 85,
                "range": 60,
                "fire_rate": 26,
                "mobility": 70,
                "control": 64,
                "overall": 62.5,
                "price": 6000
            },
            {
                "name": "SKS",
                "description": "Lightweight semi auto Carbine chambered in 7.62x39mm. This hard hitting and agile Soviet rifle focuses on utility over accuracy. It flaunts a faster fire rate than other weapons in its class, but a carefully placed round will eliminate the need for follow up shots entirely. This classic DMR has seen a lot of battles, and its unique gunsmith configurations reflect a diverse service history.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/sks.jpg",
                "class": "Marksman Rifles",
                "accuracy": 75,
                "damage": 76,
                "range": 71,
                "fire_rate": 52,
                "mobility": 59,
                "control": 73,
                "overall": 67.67,
                "price": 5800
            },
            {
                "name": "SP-R 208",
                "description": "This bolt-action marksman rifle comes as one of the most accurate weapons in its class and with a breadth of customization options. From alternate ammo choices to bolt assembly changes and more, no matter how this weapon is configured, it\u2019s a powerful yet mobile tool for a marksman on the go.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/sp-r-208.jpg",
                "class": "Marksman Rifles",
                "accuracy": 76,
                "damage": 84,
                "range": 78,
                "fire_rate": 39,
                "mobility": 51,
                "control": 65,
                "overall": 65.5,
                "price": 7700
            }
        ],
        "Sniper Rifles": [
            {
                "name": "Dragunov",
                "description": "A soviet workhorse chambered in 7.62mm x 54mmR. This gas-operated semi-automatic sniper rifle allows for rapid followup shots.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/dragunov.jpg",
                "class": "Sniper Rifles",
                "accuracy": 81,
                "damage": 78,
                "range": 75,
                "fire_rate": 47,
                "mobility": 47,
                "control": 65,
                "overall": 65.5,
                "price": 5000
            },
            {
                "name": "HDR",
                "description": "Anti-material bolt action sniper rifle chambered in 12.7x108mm ammunition. 745 gr bullets have a lower muzzle velocity, but remains devastating even at very long ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/hdr.jpg",
                "class": "Sniper Rifles",
                "accuracy": 83,
                "damage": 86,
                "range": 83,
                "fire_rate": 36,
                "mobility": 43,
                "control": 65,
                "overall": 66.0,
                "price": 6000
            },
            {
                "name": "AX-50",
                "description": "Hard hitting, bolt action sniper rifle with .50 cal BMG ammunition. Its tungsten sabot tipped bullets are fast and powerful, but require precise shots over long distances.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/ax-50.jpg",
                "class": "Sniper Rifles",
                "accuracy": 82,
                "damage": 85,
                "range": 79,
                "fire_rate": 38,
                "mobility": 44,
                "control": 70,
                "overall": 66.33,
                "price": 6000
            },
            {
                "name": "Rytec AMR",
                "description": "This semi-automatic Anti-Material Rifle is chambered in .50 BMG for dominant long-range assaults. A 25x59mm high-explosive payload variant is officially listed ad \"experimental\", but had been deployed on multiple classified mission with great effectiveness.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/Rytec-AMR.jpg",
                "class": "Sniper Rifles",
                "accuracy": 80,
                "damage": 84,
                "range": 78,
                "fire_rate": 50,
                "mobility": 40,
                "control": 65,
                "overall": 66.17,
                "price": 6500
            }
        ],
        "Handguns": [
            {
                "name": "X16",
                "description": "Semi-automatic pistol chambered in .45 ACP ammunition. A reliable fall back when you find yourself in close quarters.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/x16.jpg",
                "class": "Handguns",
                "accuracy": 55,
                "damage": 57,
                "range": 42,
                "fire_rate": 58,
                "mobility": 81,
                "control": 70,
                "overall": 60.5,
                "price": 1000
            },
            {
                "name": "1911",
                "description": "A well rounded semi-automatic side arm with a moderate rate of fire. Slightly more range than your average .45 ACP pistol.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/1911.jpg",
                "class": "Handguns",
                "accuracy": 55,
                "damage": 59,
                "range": 44,
                "fire_rate": 55,
                "mobility": 80,
                "control": 69,
                "overall": 60.33,
                "price": 1000
            },
            {
                "name": ".357",
                "description": "Double action revolver firing .357 Magnum ammunition for powerful damage over extended ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/357.jpg",
                "class": "Handguns",
                "accuracy": 60,
                "damage": 63,
                "range": 56,
                "fire_rate": 44,
                "mobility": 76,
                "control": 65,
                "overall": 60.67,
                "price": 1500
            },
            {
                "name": "M19",
                "description": "Semi-automatic 9mm pistol, excellent stability with a rapid cycle rate.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/m19.jpg",
                "class": "Handguns",
                "accuracy": 57,
                "damage": 55,
                "range": 40,
                "fire_rate": 60,
                "mobility": 82,
                "control": 72,
                "overall": 61.0,
                "price": 850
            },
            {
                "name": ".50 GS",
                "description": "The most powerful semi-automatic handgun available, deals heavy damage up to intermediate ranges.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/50-gs.jpg",
                "class": "Handguns",
                "accuracy": 54,
                "damage": 65,
                "range": 52,
                "fire_rate": 53,
                "mobility": 77,
                "control": 60,
                "overall": 60.17,
                "price": 2200
            },
            {
                "name": "Renetti",
                "description": "Well rounded semi-auto 9mm pistol. This unassuming sidearm excels in close range combat, and features gunsmithing capabilities unique to the pistol class that permit a variety of engagement strategies.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/Renetti.jpg",
                "class": "Handguns",
                "accuracy": 60,
                "damage": 55,
                "range": 41,
                "fire_rate": 62,
                "mobility": 80,
                "control": 70,
                "overall": 61.33,
                "price": 1800
            },
            {
                "name": "Sykov",
                "description": "A dependable fallback in close quarters, this double-action/single-action sidearm comes with a few custom gunsmith mods that make it an outstanding addition to any arsenal.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/sykov.jpg",
                "class": "Handguns",
                "accuracy": 53,
                "damage": 57,
                "range": 43,
                "fire_rate": 57,
                "mobility": 80,
                "control": 71,
                "overall": 60.17,
                "price": 1200
            }
        ],
        "Launchers": [
            {
                "name": "PILA",
                "description": "Portable infrared surface-to-air missile with a free-fire option. Self propelled missiles has a higher speed, and moderate explosive yield.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/pila.jpg",
                "class": "Launchers",
                "accuracy": 68,
                "damage": 82,
                "range": 90,
                "fire_rate": 25,
                "mobility": 47,
                "control": 30,
                "overall": 57.0,
                "price": 2100
            },
            {
                "name": "Strela-P",
                "description": "84mm recoilless rifle lobs an explosive projectile at a very high velocity. The unguided armor piercing round has a low explosive yield, but is devastating against vehicles on contact.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/strela-p.jpg",
                "class": "Launchers",
                "accuracy": 70,
                "damage": 88,
                "range": 87,
                "fire_rate": 30,
                "mobility": 47,
                "control": 35,
                "overall": 59.5,
                "price": 1900
            },
            {
                "name": "JOKR",
                "description": "Fire and forget lock-on portable missile launcher with a large explosive yield. Infrared guided missiles take a top-attack trajectorym, ensuring destruction of heavily armored vehicles.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/jokr.jpg",
                "class": "Launchers",
                "accuracy": 90,
                "damage": 80,
                "range": 95,
                "fire_rate": 25,
                "mobility": 42,
                "control": 40,
                "overall": 62.0,
                "price": 3400
            },
            {
                "name": "RPG-7",
                "description": "Unguided, self-propelled rocket launcher fires a slower projectile with a high-explosive yield.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/rpg-7.jpg",
                "class": "Launchers",
                "accuracy": 56,
                "damage": 86,
                "range": 85,
                "fire_rate": 30,
                "mobility": 49,
                "control": 40,
                "overall": 57.67,
                "price": 2000
            },
            {
                "name": "MGL-32 Grenade Launcher",
                "description": "The MGL-32 Grenade Launcher is exclusive to Modern Warfare's campaign and Special Ops. It also appears in Call of Duty Warzone Battle Royale as legendary loot.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/MGL-32-Grenade-Launcher.jpg",
                "class": "Launchers",
                "accuracy": 55,
                "damage": 84,
                "range": 83,
                "fire_rate": 28,
                "mobility": 52,
                "control": 30,
                "overall": 55.33,
                "price": 3000
            }
        ],
        "Melee": [
            {
                "name": "Combat Knife",
                "description": "CQC tactical knife. Standard military issue, employed for fast, quiet, and deadly wetwork.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/combat-knife.jpg",
                "class": "Melee",
                "accuracy": 0,
                "damage": 90,
                "range": 5,
                "fire_rate": 0,
                "mobility": 80,
                "control": 0,
                "overall": 29.17,
                "price": 250
            },
            {
                "name": "Kali Sticks",
                "description": "Dual wielding batons allow operators to approach their targets with great agility. Sturdy, lightweight design enables rapid attacks for zoning your enemies.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/kali-sticks.jpg",
                "class": "Melee",
                "accuracy": 0,
                "damage": 84,
                "range": 8,
                "fire_rate": 0,
                "mobility": 82,
                "control": 35,
                "overall": 34.83,
                "price": 650
            },
            {
                "name": "Dual Kodachis",
                "description": "Hand forged carbon steel blades provide the sharpest edge possible for silently slicing through your enemies.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/dual-kodachis.jpg",
                "class": "Melee",
                "accuracy": 0,
                "damage": 92,
                "range": 11,
                "fire_rate": 0,
                "mobility": 75,
                "control": 31,
                "overall": 34.83,
                "price": 450
            },
            {
                "name": "Riot Shield",
                "description": "Ballistic-proof and explosive-resistant shield with increased melee damage.",
                "image": "https://www.gamesatlas.com/images/cod-modern-warfare/weapons/riot-shield.jpg",
                "class": "Melee",
                "accuracy": 0,
                "damage": 90,
                "range": 5,
                "fire_rate": 0,
                "mobility": 80,
                "control": 0,
                "overall": 29.17,
                "price": 2000
            }
        ]
    }

    return weapons
}

export default getWeapons;